baseURL: https://yeshwanthlm.in
title: Yeshwanth L M
paginate: 6
theme: charlolamode



menu:
    main:
        - name: About
          url: about/
          weight: 30
        #- name: Blog
        #  url: blog/
        #  weight: 20
        # - name: Categories
        #   url: categories/
        #   weight: 10
        #- name: Notes
        #  url: notes/
        #  weight: 10
        - name: Public Speaking
          url: publicspeaking/
        - name: IEEE
          url: ieee/
        - name: Achievements
          url: achievements/
        - name: Contact
          url: contact/


params:
    author: Yeshwanth L M
    description: Hi, I am Yeshwanth, a Presales Solutions Engineer at Confluent India and Cloud/DevOps enthusiast.


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Yeshwanth 👋
        description: Hi, I am Yeshwanth, a Presales Solutions Engineer at Confluent India and Cloud/DevOps Enthusiast.
        imageUrl: "/images/profile.jpg"
        imageTitle: Yeshwanth L M
        imageWidth: 200
        imageHeight: 200
        buttons:
            - name: Don't click me
              url: https://www.youtube.com/@amonkincloud
    mainSections:
      - articles

    socialIcons:
        - name: github
          url: "https://github.com/yeshwanthlm"
        - name: youtube
          url: "https://youtube.com/@amonkincloud"
        - name: twitter
          url: "https://twitter.com/yeshwanth_l_m"
        - name: linkedin
          url: "https://www.linkedin.com/in/yeshwanth-l-m/"
        - name: instagram
          url: "https://instagram.com/yeshwanthlm"


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

